import { z } from 'zod';

import {
  reqNum,
  reqPct,
  reqStr,
  reqFloat,
  optNum,
  reqTime,
  optStr,
} from '../../lib/convert';

const DatosObservaciones = z.object({
  observacion: reqStr('Obervaciones Esmalte'),
});

const DatosTabla = z.object({
  hora: reqTime('Hora'),
  tipo_concepto: reqStr('Tipo Concepto'),
  a1: optNum('a1'),
  a2: optNum('a2'),
  a3: optNum('a3'),
  b1: optNum('b1'),
  b2: optNum('b2'),
  b3: optNum('b3'),
  c1: optNum('c1'),
  c2: optNum('c2'),
  c3: optNum('c3'),
  d1: optNum('d1'),
  d2: optNum('d2'),
  d3: optNum('d3'),
  cajas_segunda: optNum('Cajas segunda'),
  defecto_segundaN1: optNum('defecto_segundaN1'),
  defecto_segundaN2: optNum('defecto_segundaN2'),
  defecto_segundaN3: optNum('defecto_segundaN3'),
  defecto_segundaN4: optNum('defecto_segundaN4'),
  defecto_segundaN5: optNum('defecto_segundaN5'),
  defecto_segundaN6: optNum('defecto_segundaN6'),
  defecto_segundaN7: optNum('defecto_segundaN7'),
  defecto_segundaN8: optNum('defecto_segundaN8'),
  defecto_segundaN9: optNum('defecto_segundaN9'),
  defecto_segundaN10: optNum('defecto_segundaN10'),
  cajas_tercera: optNum('cajas_tercera'),
  defecto_terceraN1: optNum('defecto_tercera_1'),
  defecto_terceraN2: optNum('defecto_tercera_2'),
  defecto_terceraN3: optNum('defecto_tercera_3'),
  defecto_terceraN4: optNum('defecto_tercera_4'),
  defecto_terceraN5: optNum('defecto_tercera_5'),
  defecto_terceraN6: optNum('defecto_tercera_6'),
  defecto_terceraN7: optNum('defecto_tercera_7'),
  cajas_casco: optNum('Cajas casco'),
  defecto_cascoN1: optNum('Defecto casco1'),
  defecto_cascoN2: optNum('Defecto casco2'),
  defecto_cascoN3: optNum('Defecto casco3'),
  defecto_cascoN4: optNum('Defecto casco4'),
  espacio_min: optNum('Espacion min'),
});

export const DatosEmbalaje = z.object({
  fecha: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'Formato AAAA-MM-DD'),
  producto: reqStr('Producto'),
  horno: optStr('horno'),
  formato: optStr('Formato'),
  turno: reqStr('Turno'),
  supervisor_turno: reqStr('Supervisor de turno'),
  operador: reqStr('Operador'),
  grupo: reqStr('Grupo'),
  segunda_defectoN1: optNum('segunda defecto 1'),
  segunda_defectoN2: optNum('segunda defecto 2'),
  segunda_defectoN3: optNum('segunda defecto 3'),
  segunda_defectoN4: optNum('segunda defecto 4'),
  segunda_defectoN5: optNum('segunda defecto 5'),
  segunda_defectoN6: optNum('segunda defecto 6'),
  segunda_defectoN7: optNum('segunda defecto 7'),
  segunda_defectoN8: optNum('segunda defecto 8'),
  segunda_defectoN9: optNum('segunda defecto 9'),
  segunda_defectoN10: optNum('segunda defecto 10'),
  tercera_defectoN1: optNum('Tercera defecto 1'),
  tercera_defectoN2: optNum('Tercera defecto 2'),
  tercera_defectoN3: optNum('Tercera defecto 3'),
  tercera_defectoN4: optNum('Tercera defecto 4'),
  tercera_defectoN5: optNum('Tercera defecto 5'),
  tercera_defectoN6: optNum('Tercera defecto 6'),
  tercera_defectoN7: optNum('Tercera defecto 7'),
  casco_defectoN1: optNum('casco defecto 1'),
  casco_defectoN2: optNum('casco defecto 2'),
  casco_defectoN3: optNum('casco defecto 3'),
  casco_defectoN4: optNum('casco defecto 4'),

  tabla_seleccion_embalaje: z.array(DatosTabla).min(0).max(8).default([]),
  observacion_embalaje: z.array(DatosObservaciones).min(0).default([]),
});
